name: Enforce Contribution Guidelines

on:
  pull_request:
    types: [opened, edited]

jobs:
  enforce-guidelines:
    runs-on: ubuntu-latest

    steps:
    - name: Check Pull Request Title
      uses: actions/github-script@v5
      with:
        script: |
          const titleRegex = /^\[(HW|EC|LABS|NOTES)\].+?\[(.+?)\]$/gm;
          const title = github.event.pull_request.title;
          if (!titleRegex.test(title)) {
            const errorMessage = `Pull request title does not follow the specified convention. Please refer to [CONTRIBUTING.md](../CONTRIBUTING.md) for guidelines on how to format your pull request title.`;
            console.error(errorMessage);
            github.issues.createComment({
              issue_number: github.context.issue.number,
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              body: errorMessage
            });
            core.setFailed("Pull request title does not follow the specified convention.");
          }
